# Generated by Django 5.1.4 on 2025-02-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.TextField(default='', max_length=100)),
                ('sub_category', models.TextField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(default='', max_length=300)),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
